### PR TITLE
Fix _nl and _de conflicts with master

### PR DESCRIPTION
**Pull request by silverailscolo**
these are the new values from jmrit.signalling.entryexit in master

### CODE REVIEW

**Comment by silverailscolo** [comment]
@dsand47 Are you able to merge this yourself into your private -move branch?

**Comment by dsand47** [comment]
@silverailscolo Yes I was.  However, AppVeyor says that it is **unable to build an non-mergable pull request**.  I suspect this message occurs because the conflict still exists.  

What we need to do is figure out how to remove the delete of **signalling/entryexit/Bundle_de.properties** from commit c02ca34.

The problem is that I did not do a **rename with changes**.  I created new Bundle... files at the target location that were the result of merging SignalBundle... and entryexit/Bundle...  I then deleted entryexit/Bundle...

Dave Sand

**Comment by silverailscolo** [comment]
As the folder ``signalling/entryexit`` was also deleted (not shown as a change) it would make sense it's impossible to resolve some changed lines. We might try to put back a dummy folder containing a copy of  the Bundle_de.properties file.

**Comment by dsand47** [comment]
I have decided to start over with a fresh sync from master.

The changes have all been applied.  I just need to test to make sure that I did not miss something.

Dave Sand

**Pull request merged**
